<?php

use Illuminate\Database\Seeder;

class BureauVotesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	//1
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>1,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>1,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>1,
        ]);
        //2
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>2,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>2,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>2,
        ]);
        //3
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>3,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>3,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>3,
        ]);
        //4
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>4,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>4,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>4,
        ]);
        //5
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>5,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>5,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>5,
        ]);

        //6
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>6,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>6,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>6,
        ]);
        //7
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>7,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>7,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>7,
        ]);
        //8
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>8,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>8,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>8,
        ]);
        //9
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>9,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>9,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>9,
        ]);
        //10
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>10,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>10,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>10,
        ]);

        //11
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>11,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>11,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>11,
        ]);
        //12
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>12,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>12,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>12,
        ]);
        //13
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>13,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>13,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>13,
        ]);
        //14
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>14,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>14,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>14,
        ]);

        //15
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>15,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>15,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>15,
        ]);
        //16
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>16,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>16,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>16,
        ]);
        //17
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>17,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>17,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>17,
        ]);
        //18
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>18,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>18,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>18,
        ]);
        //19
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>19,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>19,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>19,
        ]);

        //20
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>20,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>20,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>20,
        ]);
        //21
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>21,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>21,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>21,
        ]);
        //22
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>22,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>22,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>22,
        ]);
        //23
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>23,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>23,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>23,
        ]);
        //24
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>24,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>24,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>24,
        ]);
        //25
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>25,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>25,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>25,
        ]);
        //26
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV1",
        	'centre_vote_id'=>26,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV2",
        	'centre_vote_id'=>26,
        ]);
        DB::table('bureau_votes')->insert([
        	'numero'=>"BV3",
        	'centre_vote_id'=>26,
        ]);

    }
}
